### PR TITLE
Explicitly reset ::placeholder

### PR DESCRIPTION
**Pull request by Awjin**

### CODE REVIEW

**Comment by elektronik2k5** [comment]
Hi @Awjin and thanks for your contribution. Can you please describe what issue does your change aim to solve and perhaps add a screenshot of before/after?

**Comment by elad2412** [comment]
Issue closed, no explanation of the problem.

Before closing tested on CodePen: https://codepen.io/elad2412/pen/ExbgomP/ba66596cdd50ad63252f9f7e2b011899

Checked on Chrome, Firefox, and Safari on Macbook pro-2021 with MacOs Monterey (12.1)

**Comment by Awjin** [comment]
Browsers set a default opacity on placeholder text.

No reset:
Screen Shot 2022-02-04 at 14 32 47

With reset:
Screen Shot 2022-02-04 at 14 32 38

**Comment by elad2412** [comment]
@Awjin, thanks for the explanation.

Instead, I added a separate treatment not to complicate the global reset.

```css
/* reset default text opacity of input placeholder */
::placeholder{
    all:unset;
}
```

Thanks for this flag-up. Feature added from version 1.4.8

**Pull request closed without merging**
