### PR TITLE
Change `max-width` to `max-inline-size`

### PR DESCRIPTION
**Pull request by vicsantizo**
Change `max-width` to `max-inline-size` in order to control layout through logical rather than physical, direction and dimension mappings. This helps with making websites internationally compatible.  https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Logical_Properties

### CODE REVIEW

**Comment by graymatter00** [comment]
According to [https://developer.mozilla.org/en-US/docs/Web/CSS/max-inline-size](url) and [https://caniuse.com/?search=max-inline-size](url), `max-inline-size` is only supported on iOS with Safari version 12.2 and above.  Previous Safari versions require the `-webkit-` prefix.

According to [https://stackoverflow.com/questions/8627968/what-version-of-mobile-safari-comes-with-each-version-of-ios](url), Safari version 12.1 is the highest version supported on iPhone 6.  I have confirmed this with an iPhone 6 device that I have for testing. On this device the latest available iOS version is 12.5.5 with the latest available Safari version being 12.1.  See attached screenshots. 

My understanding is that iPhone 6 will not receive further Safari updates, even though there are a surprising number of iPhone 6 units still in use.

Therefore, if this Pull Request is implemented, please consider adding the `-webkit-` prefixed property as well.

```CSS
img {
    -webkit-max-inline-size: 100%;
    max-inline-size: 100%;
}
```

**Comment by graymatter00** [comment]
Please excuse my ignorance, but I don't know what "closed this by deleting the head repository" means.  Could someone please explain?

**Comment by vicsantizo** [comment]
The pr was closed since I deleted the forked repo

**Comment by graymatter00** [comment]
I see.  Thanks for the explanation.

Although, that's a shame.  I agreed with your suggested change.  It would be nice to know why it wasn't merged.  Perhaps you could re-submit it as a suggestion in Issues.

**Pull request closed without merging**
